sudo: required

env:
  - VERSION=2.6
  - VERSION=3.0
  - VERSION=3.2
  - VERSION=3.4

services:
  - docker

before_install:
  - docker version
  - docker network create --driver=bridge --subnet=192.168.0.0/16 --opt="com.docker.network.driver.mtu=1450" --opt="com.docker.network.bridge.name=redd0" microbox
  - sudo apt-get -y install python-pip
  - sudo pip install docker==2.7.0 docker-squash
  - git clone https://github.com/mu-box/microbox-hooks-mongodb.git hooks
  - docker build -t mubox/mongodb:$VERSION ./$VERSION

script:
  - sudo stdbuf -oL test/run_all.sh $VERSION
  - sudo stdbuf -oL hooks/test/run_all.sh ${VERSION}

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - "echo \"Branch: '$BRANCH'; Version: '$VERSION'\";"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker build -t ${NAMESPACE}/mongodb ./${VERSION};
  - docker-squash -t ${NAMESPACE}/mongodb:squashed -f mubox/base --tmp-dir /var/tmp/squasher ${NAMESPACE}/mongodb
  # `$VERSION-beta` tag is always pushed (main or any dev branch)
  - docker tag ${NAMESPACE}/mongodb:squashed ${NAMESPACE}/mongodb:${VERSION}-beta;
  - docker push ${REMOTE}${NAMESPACE}/mongodb:${VERSION}-beta;
  # `beta` tag is always pushed (main or any dev branch)
  - if [ "$VERSION" == "3.0" ]; then
    docker tag ${NAMESPACE}/mongodb:squashed ${NAMESPACE}/mongodb:beta;
    docker push ${REMOTE}${NAMESPACE}/mongodb:beta;
    fi
  # `latest` tag is only pushed on main && most recent version
  - if [ "$BRANCH" == "main" ] && [ "$VERSION" == "3.0" ]; then
    docker tag ${NAMESPACE}/mongodb:squashed ${NAMESPACE}/mongodb;
    docker push ${REMOTE}${NAMESPACE}/mongodb;
    fi
  # `$VERSION` (latest/stable implied) tag is only pushed on main. tag branch for clarity otherwise (`$VERSION-$BRANCH`)
  - if [ "$BRANCH" == "main" ]; then
    docker tag ${NAMESPACE}/mongodb:squashed ${NAMESPACE}/mongodb:${VERSION};
    docker push ${REMOTE}${NAMESPACE}/mongodb:${VERSION};
    else
    docker tag ${NAMESPACE}/mongodb:squashed ${NAMESPACE}/mongodb:${VERSION}-${BRANCH//\//_};
    docker push ${REMOTE}${NAMESPACE}/mongodb:${VERSION}-${BRANCH//\//_};
    fi
